###
GET https://rqygsodbcvrutuezcjts.supabase.co/
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxeWdzb2RiY3ZydXR1ZXpjanRzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4MTcwMzA2MiwiZXhwIjoxOTk3Mjc5MDYyfQ.ojuwZBbg_uAwZ2JfVx8tz_WVYn9VsChu7xdP9rRUkcI

###
POST https://rqygsodbcvrutuezcjts.supabase.co/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxeWdzb2RiY3ZydXR1ZXpjanRzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4MTcwMzA2MiwiZXhwIjoxOTk3Mjc5MDYyfQ.ojuwZBbg_uAwZ2JfVx8tz_WVYn9VsChu7xdP9rRUkcI

{
  "text": "Order pizza"
}






